server:
  port: 8001
spring:
  application:
    name: home-ops
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.154:8848
        username: nacos
        password: nacos
        namespace: public
      config:
        group: DEFAULT_GROUP
        server-addr: 192.168.2.154:8848
  config:
    import:
      - optional:nacos:home-ops.yml
