spring:
  application:
    name: home-user
  cloud:
    nacos:
      discovery:
        register-enabled: true # 启用注册,本地环境设置为false避免混乱
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:home-user.yml
  aop:
    auto: true
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  #  TODO:datasource临时测试用, 后续接入nacos-config
  datasource:
    url: jdbc:mysql://localhost:3306/homeedu?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 3000
  #  Springboot2.6+ 解决swagger启动报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  banner:
    location: banner.txt

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
    banner: false


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.amur.home.user.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-host: true
    enable-host-text: 127.0.0.1/home-user #填写为网关地址,用于在网管聚合界面调试接口
  basic:
    enable: true
    username: admin
    password: 123456
  # 开启生产环境屏蔽
  production: false

server:
  port: 8701

grpc:
  server:
    port: 9701
  client:
    home-tinyid:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      address: 'discovery:///home-tinyid'
      negotiation-type: plaintext
#logging:
#  level:
#    root: DEBUG

tinyid:
  token: 0f673adf80504e2eaa552f5d791b644c
  bizType: home