spring:
  application:
    name: home-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.154:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.2.154:8848
  config:
    import:
      - optional:nacos:home-user.yml
  aop:
    auto: true
    proxy-target-class: true


  #  TODO:datasource临时测试用, 后续接入nacos-config
  datasource:
    url: jdbc:mysql://localhost:3306/homeedu?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 3000
  zipkin:
    enabled: true
    base-url: http://192.168.2.154:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

server:
  port: 8701