apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    com.amur.service: db-claim0
  name: db-claim0
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 20Gi
    hostPath:
        path: /tmp/data
    persistentVolumeReclaimPolicy: Retain
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    com.amur.service: db-claim0
  name: db-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    com.amur.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      com.amur.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        com.amur.network/compose-amur: "true"
        com.amur.service: db
    spec:
      imagePullSecrets:
        - name: aliyun
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: nacos
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: user
          image: registry.cn-beijing.aliyuncs.com/amur/db:latest
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 10
          name: db
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-claim0
      hostname: db
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: db-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    com.amur.service: db
  name: db
spec:
  type: NodePort
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    com.amur.service: db
status:
  loadBalancer: {}
