apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    com.amur.service: home-rtc
  name: home-rtc
spec:
  replicas: 1
  selector:
    matchLabels:
      com.amur.service: home-rtc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        com.amur.network/compose-amur: "true"
        com.amur.service: home-rtc
    spec:
      imagePullSecrets:
        - name: aliyun
      containers:
        - env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx256m
            - name: SPRING_CLOUD_NACOS_CONFIG_GROUP
              value: DEFAULT_GROUP
            - name: SPRING_CLOUD_NACOS_CONFIG_SERVERADDR
              value: nacos:8848
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR
              value: nacos:8848
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db:3306/homeedu?characterEncoding=utf8&connectTimeout=5000&socketTimeout=10000&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          image: registry.cn-beijing.aliyuncs.com/amur/home-rtc:latest
          name: home-rtc
          ports:
            - containerPort: 8703
            - containerPort: 9703
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    com.amur.service: home-rtc
  name: home-rtc
spec:
  ports:
    - name: "8703"
      port: 8703
      targetPort: 8703
    - name: "9703"
      port: 9703
      targetPort: 9703
  selector:
    com.amur.service: home-rtc
status:
  loadBalancer: {}
