apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    com.amur.network/compose-skywalking: "true"
    com.amur.service: ui
  name: ui
spec:
  containers:
    - env:
        - name: SW_PROXY_TARGET
          value: http://oap:12800
        - name: TZ
          value: Asia/Shanghai
      image: registry.cn-beijing.aliyuncs.com/amur/skywalking-ui:latest
      name: skywalking-ui
      ports:
        - containerPort: 8808
      resources: {}
  restartPolicy: OnFailure
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    com.amur.service: ui
  name: ui
spec:
  type: NodePort
  ports:
    - name: "8808"
      port: 8808
      targetPort: 8808
      # nodePort: 8808
  selector:
    com.amur.service: ui
status:
  loadBalancer: {}
