server:
  port: 8002
spring:
  application:
    name: home-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:home-auth.yml
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    lettuce:
#      pool:
#        max-active: 500
#        max-wait: -1ms
#        max-idle: 100
#        min-idle: 10
#    timeout: 1000ms
grpc:
  server:
    port: 9002


