server:
  port: 8002
spring:
  application:
    name: home-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:home-auth.yml
grpc:
  server:
    port: 9002
