// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home.proto

package com.amur.home.user.rpc;

public final class HomeServiceProto {
  private HomeServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhome.proto\022\026com.amur.home.user.rpc\032\023Se" +
      "rviceResult.protoB,\n\026com.amur.home.user." +
      "rpcB\020HomeServiceProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.amur.home.user.rpc.ServiceResultProto.getDescriptor(),
        });
    com.amur.home.user.rpc.ServiceResultProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
