#!/bin/zsh

# +--------------------  WARNING  ----------------------+
# | This script is automatically generated by Chat-GPT  |
# |      USE THIS SCRIPT AT YOUR OWN RISK!!!!!!!        |
# +-----------------------------------------------------+

# Check system type
if [ -f /etc/os-release ]; then
  # Linux system
  . /etc/os-release
  OS=$ID
  VER=$VERSION_ID
elif [ "$(uname)" == "Darwin" ]; then
  # macOS
  OS="macos"
  VER=$(sw_vers -productVersion | awk -F '.' '{print $1 "." $2}')
else
  echo "Unsupported operating system"
  exit 1
fi

echo "Detected operating system: $OS $VER"

# Install dependencies
if [ "$OS" == "ubuntu" ]; then
  # Update package source to Tsinghua University source
  sudo sed -i 's/http:\/\/.*\/ubuntu\//https:\/\/mirrors.tuna.tsinghua.edu.cn\/ubuntu\//g' /etc/apt/sources.list
  sudo apt-get update

  if [ "$VER" == "16.04" ] || [ "$VER" == "18.04" ] || [ "$VER" == "20.04" ] || [ "$VER" == "22.04" ]; then
    # Install Docker
    sudo apt-get install -y docker.io docker-compose
  else
    echo "Unsupported Ubuntu version"
    exit 1
  fi
elif [ "$OS" == "centos" ]; then
  # Update package source to Tsinghua University source
  sudo sed -i 's/http:\/\/.*centos.*\/$releasever\//https:\/\/mirrors.tuna.tsinghua.edu.cn\/centos\/$releasever\//g' /etc/yum.repos.d/CentOS-Base.repo

  if [ "$VER" == "6" ] || [ "$VER" == "7" ] || [ "$VER" == "8" ]; then
    # Install Docker
    sudo yum install -y yum-utils device-mapper-persistent-data lvm2
    sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo yum install -y docker-ce docker-ce-cli containerd.io docker-compose
  else
    echo "Unsupported CentOS version"
    exit 1
  fi
elif [ "$OS" == "macos" ]; then
  # Check macOS version
  if [ "$(printf "%d\n" "$(echo "$VER >= 10.14" | bc)" -ne 1 ]]; then
    echo "Unsupported macOS version"
    exit 1
  fi

  # Install Docker
  brew install docker docker-compose
else
  echo "Unsupported operating system"
  exit 1
fi

echo "Docker and Docker Compose installed successfully"
