// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.amur.home.auth.rpc;

public final class AuthServiceProto {
  private AuthServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetAuthByIdRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amur.home.auth.rpc.GetAuthByIdRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code com.amur.home.auth.rpc.GetAuthByIdRequest}
   */
  public static final class GetAuthByIdRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amur.home.auth.rpc.GetAuthByIdRequest)
      GetAuthByIdRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetAuthByIdRequest.newBuilder() to construct.
    private GetAuthByIdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetAuthByIdRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetAuthByIdRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetAuthByIdRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_GetAuthByIdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_GetAuthByIdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest.class, com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest)) {
        return super.equals(obj);
      }
      com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest other = (com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amur.home.auth.rpc.GetAuthByIdRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amur.home.auth.rpc.GetAuthByIdRequest)
        com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_GetAuthByIdRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_GetAuthByIdRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest.class, com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest.Builder.class);
      }

      // Construct using com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_GetAuthByIdRequest_descriptor;
      }

      @java.lang.Override
      public com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest getDefaultInstanceForType() {
        return com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest build() {
        com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest buildPartial() {
        com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest result = new com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest) {
          return mergeFrom((com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest other) {
        if (other == com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amur.home.auth.rpc.GetAuthByIdRequest)
    }

    // @@protoc_insertion_point(class_scope:com.amur.home.auth.rpc.GetAuthByIdRequest)
    private static final com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest();
    }

    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetAuthByIdRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetAuthByIdRequest>() {
      @java.lang.Override
      public GetAuthByIdRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetAuthByIdRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetAuthByIdRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetAuthByIdRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetAuthByIdResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amur.home.auth.rpc.GetAuthByIdResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
     * @return Whether the auth field is set.
     */
    boolean hasAuth();
    /**
     * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
     * @return The auth.
     */
    com.amur.home.auth.rpc.AuthServiceProto.UserAuth getAuth();
    /**
     * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
     */
    com.amur.home.auth.rpc.AuthServiceProto.UserAuthOrBuilder getAuthOrBuilder();
  }
  /**
   * Protobuf type {@code com.amur.home.auth.rpc.GetAuthByIdResponse}
   */
  public static final class GetAuthByIdResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amur.home.auth.rpc.GetAuthByIdResponse)
      GetAuthByIdResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetAuthByIdResponse.newBuilder() to construct.
    private GetAuthByIdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetAuthByIdResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetAuthByIdResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetAuthByIdResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.amur.home.auth.rpc.AuthServiceProto.UserAuth.Builder subBuilder = null;
              if (auth_ != null) {
                subBuilder = auth_.toBuilder();
              }
              auth_ = input.readMessage(com.amur.home.auth.rpc.AuthServiceProto.UserAuth.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(auth_);
                auth_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_GetAuthByIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_GetAuthByIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse.class, com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse.Builder.class);
    }

    public static final int AUTH_FIELD_NUMBER = 1;
    private com.amur.home.auth.rpc.AuthServiceProto.UserAuth auth_;
    /**
     * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
     * @return Whether the auth field is set.
     */
    @java.lang.Override
    public boolean hasAuth() {
      return auth_ != null;
    }
    /**
     * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
     * @return The auth.
     */
    @java.lang.Override
    public com.amur.home.auth.rpc.AuthServiceProto.UserAuth getAuth() {
      return auth_ == null ? com.amur.home.auth.rpc.AuthServiceProto.UserAuth.getDefaultInstance() : auth_;
    }
    /**
     * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
     */
    @java.lang.Override
    public com.amur.home.auth.rpc.AuthServiceProto.UserAuthOrBuilder getAuthOrBuilder() {
      return getAuth();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (auth_ != null) {
        output.writeMessage(1, getAuth());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (auth_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAuth());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse)) {
        return super.equals(obj);
      }
      com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse other = (com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse) obj;

      if (hasAuth() != other.hasAuth()) return false;
      if (hasAuth()) {
        if (!getAuth()
            .equals(other.getAuth())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAuth()) {
        hash = (37 * hash) + AUTH_FIELD_NUMBER;
        hash = (53 * hash) + getAuth().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amur.home.auth.rpc.GetAuthByIdResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amur.home.auth.rpc.GetAuthByIdResponse)
        com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_GetAuthByIdResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_GetAuthByIdResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse.class, com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse.Builder.class);
      }

      // Construct using com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (authBuilder_ == null) {
          auth_ = null;
        } else {
          auth_ = null;
          authBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_GetAuthByIdResponse_descriptor;
      }

      @java.lang.Override
      public com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse getDefaultInstanceForType() {
        return com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse build() {
        com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse buildPartial() {
        com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse result = new com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse(this);
        if (authBuilder_ == null) {
          result.auth_ = auth_;
        } else {
          result.auth_ = authBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse) {
          return mergeFrom((com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse other) {
        if (other == com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse.getDefaultInstance()) return this;
        if (other.hasAuth()) {
          mergeAuth(other.getAuth());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.amur.home.auth.rpc.AuthServiceProto.UserAuth auth_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amur.home.auth.rpc.AuthServiceProto.UserAuth, com.amur.home.auth.rpc.AuthServiceProto.UserAuth.Builder, com.amur.home.auth.rpc.AuthServiceProto.UserAuthOrBuilder> authBuilder_;
      /**
       * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
       * @return Whether the auth field is set.
       */
      public boolean hasAuth() {
        return authBuilder_ != null || auth_ != null;
      }
      /**
       * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
       * @return The auth.
       */
      public com.amur.home.auth.rpc.AuthServiceProto.UserAuth getAuth() {
        if (authBuilder_ == null) {
          return auth_ == null ? com.amur.home.auth.rpc.AuthServiceProto.UserAuth.getDefaultInstance() : auth_;
        } else {
          return authBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
       */
      public Builder setAuth(com.amur.home.auth.rpc.AuthServiceProto.UserAuth value) {
        if (authBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          auth_ = value;
          onChanged();
        } else {
          authBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
       */
      public Builder setAuth(
          com.amur.home.auth.rpc.AuthServiceProto.UserAuth.Builder builderForValue) {
        if (authBuilder_ == null) {
          auth_ = builderForValue.build();
          onChanged();
        } else {
          authBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
       */
      public Builder mergeAuth(com.amur.home.auth.rpc.AuthServiceProto.UserAuth value) {
        if (authBuilder_ == null) {
          if (auth_ != null) {
            auth_ =
              com.amur.home.auth.rpc.AuthServiceProto.UserAuth.newBuilder(auth_).mergeFrom(value).buildPartial();
          } else {
            auth_ = value;
          }
          onChanged();
        } else {
          authBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
       */
      public Builder clearAuth() {
        if (authBuilder_ == null) {
          auth_ = null;
          onChanged();
        } else {
          auth_ = null;
          authBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
       */
      public com.amur.home.auth.rpc.AuthServiceProto.UserAuth.Builder getAuthBuilder() {
        
        onChanged();
        return getAuthFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
       */
      public com.amur.home.auth.rpc.AuthServiceProto.UserAuthOrBuilder getAuthOrBuilder() {
        if (authBuilder_ != null) {
          return authBuilder_.getMessageOrBuilder();
        } else {
          return auth_ == null ?
              com.amur.home.auth.rpc.AuthServiceProto.UserAuth.getDefaultInstance() : auth_;
        }
      }
      /**
       * <code>.com.amur.home.auth.rpc.UserAuth auth = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amur.home.auth.rpc.AuthServiceProto.UserAuth, com.amur.home.auth.rpc.AuthServiceProto.UserAuth.Builder, com.amur.home.auth.rpc.AuthServiceProto.UserAuthOrBuilder> 
          getAuthFieldBuilder() {
        if (authBuilder_ == null) {
          authBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.amur.home.auth.rpc.AuthServiceProto.UserAuth, com.amur.home.auth.rpc.AuthServiceProto.UserAuth.Builder, com.amur.home.auth.rpc.AuthServiceProto.UserAuthOrBuilder>(
                  getAuth(),
                  getParentForChildren(),
                  isClean());
          auth_ = null;
        }
        return authBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amur.home.auth.rpc.GetAuthByIdResponse)
    }

    // @@protoc_insertion_point(class_scope:com.amur.home.auth.rpc.GetAuthByIdResponse)
    private static final com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse();
    }

    public static com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetAuthByIdResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetAuthByIdResponse>() {
      @java.lang.Override
      public GetAuthByIdResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetAuthByIdResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetAuthByIdResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetAuthByIdResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amur.home.auth.rpc.AuthServiceProto.GetAuthByIdResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserAuthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amur.home.auth.rpc.UserAuth)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>repeated string roles = 3;</code>
     * @return A list containing the roles.
     */
    java.util.List<java.lang.String>
        getRolesList();
    /**
     * <code>repeated string roles = 3;</code>
     * @return The count of roles.
     */
    int getRolesCount();
    /**
     * <code>repeated string roles = 3;</code>
     * @param index The index of the element to return.
     * @return The roles at the given index.
     */
    java.lang.String getRoles(int index);
    /**
     * <code>repeated string roles = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the roles at the given index.
     */
    com.google.protobuf.ByteString
        getRolesBytes(int index);

    /**
     * <code>repeated string permissions = 4;</code>
     * @return A list containing the permissions.
     */
    java.util.List<java.lang.String>
        getPermissionsList();
    /**
     * <code>repeated string permissions = 4;</code>
     * @return The count of permissions.
     */
    int getPermissionsCount();
    /**
     * <code>repeated string permissions = 4;</code>
     * @param index The index of the element to return.
     * @return The permissions at the given index.
     */
    java.lang.String getPermissions(int index);
    /**
     * <code>repeated string permissions = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the permissions at the given index.
     */
    com.google.protobuf.ByteString
        getPermissionsBytes(int index);
  }
  /**
   * Protobuf type {@code com.amur.home.auth.rpc.UserAuth}
   */
  public static final class UserAuth extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amur.home.auth.rpc.UserAuth)
      UserAuthOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserAuth.newBuilder() to construct.
    private UserAuth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserAuth() {
      password_ = "";
      roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserAuth();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserAuth(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                roles_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              roles_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                permissions_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              permissions_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          roles_ = roles_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          permissions_ = permissions_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_UserAuth_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_UserAuth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amur.home.auth.rpc.AuthServiceProto.UserAuth.class, com.amur.home.auth.rpc.AuthServiceProto.UserAuth.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROLES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList roles_;
    /**
     * <code>repeated string roles = 3;</code>
     * @return A list containing the roles.
     */
    public com.google.protobuf.ProtocolStringList
        getRolesList() {
      return roles_;
    }
    /**
     * <code>repeated string roles = 3;</code>
     * @return The count of roles.
     */
    public int getRolesCount() {
      return roles_.size();
    }
    /**
     * <code>repeated string roles = 3;</code>
     * @param index The index of the element to return.
     * @return The roles at the given index.
     */
    public java.lang.String getRoles(int index) {
      return roles_.get(index);
    }
    /**
     * <code>repeated string roles = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the roles at the given index.
     */
    public com.google.protobuf.ByteString
        getRolesBytes(int index) {
      return roles_.getByteString(index);
    }

    public static final int PERMISSIONS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList permissions_;
    /**
     * <code>repeated string permissions = 4;</code>
     * @return A list containing the permissions.
     */
    public com.google.protobuf.ProtocolStringList
        getPermissionsList() {
      return permissions_;
    }
    /**
     * <code>repeated string permissions = 4;</code>
     * @return The count of permissions.
     */
    public int getPermissionsCount() {
      return permissions_.size();
    }
    /**
     * <code>repeated string permissions = 4;</code>
     * @param index The index of the element to return.
     * @return The permissions at the given index.
     */
    public java.lang.String getPermissions(int index) {
      return permissions_.get(index);
    }
    /**
     * <code>repeated string permissions = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the permissions at the given index.
     */
    public com.google.protobuf.ByteString
        getPermissionsBytes(int index) {
      return permissions_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      for (int i = 0; i < roles_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, roles_.getRaw(i));
      }
      for (int i = 0; i < permissions_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, permissions_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < roles_.size(); i++) {
          dataSize += computeStringSizeNoTag(roles_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRolesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < permissions_.size(); i++) {
          dataSize += computeStringSizeNoTag(permissions_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPermissionsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amur.home.auth.rpc.AuthServiceProto.UserAuth)) {
        return super.equals(obj);
      }
      com.amur.home.auth.rpc.AuthServiceProto.UserAuth other = (com.amur.home.auth.rpc.AuthServiceProto.UserAuth) obj;

      if (getId()
          != other.getId()) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getRolesList()
          .equals(other.getRolesList())) return false;
      if (!getPermissionsList()
          .equals(other.getPermissionsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      if (getRolesCount() > 0) {
        hash = (37 * hash) + ROLES_FIELD_NUMBER;
        hash = (53 * hash) + getRolesList().hashCode();
      }
      if (getPermissionsCount() > 0) {
        hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getPermissionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amur.home.auth.rpc.AuthServiceProto.UserAuth prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amur.home.auth.rpc.UserAuth}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amur.home.auth.rpc.UserAuth)
        com.amur.home.auth.rpc.AuthServiceProto.UserAuthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_UserAuth_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_UserAuth_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amur.home.auth.rpc.AuthServiceProto.UserAuth.class, com.amur.home.auth.rpc.AuthServiceProto.UserAuth.Builder.class);
      }

      // Construct using com.amur.home.auth.rpc.AuthServiceProto.UserAuth.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        password_ = "";

        roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amur.home.auth.rpc.AuthServiceProto.internal_static_com_amur_home_auth_rpc_UserAuth_descriptor;
      }

      @java.lang.Override
      public com.amur.home.auth.rpc.AuthServiceProto.UserAuth getDefaultInstanceForType() {
        return com.amur.home.auth.rpc.AuthServiceProto.UserAuth.getDefaultInstance();
      }

      @java.lang.Override
      public com.amur.home.auth.rpc.AuthServiceProto.UserAuth build() {
        com.amur.home.auth.rpc.AuthServiceProto.UserAuth result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amur.home.auth.rpc.AuthServiceProto.UserAuth buildPartial() {
        com.amur.home.auth.rpc.AuthServiceProto.UserAuth result = new com.amur.home.auth.rpc.AuthServiceProto.UserAuth(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.password_ = password_;
        if (((bitField0_ & 0x00000001) != 0)) {
          roles_ = roles_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.roles_ = roles_;
        if (((bitField0_ & 0x00000002) != 0)) {
          permissions_ = permissions_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.permissions_ = permissions_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amur.home.auth.rpc.AuthServiceProto.UserAuth) {
          return mergeFrom((com.amur.home.auth.rpc.AuthServiceProto.UserAuth)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amur.home.auth.rpc.AuthServiceProto.UserAuth other) {
        if (other == com.amur.home.auth.rpc.AuthServiceProto.UserAuth.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.roles_.isEmpty()) {
          if (roles_.isEmpty()) {
            roles_ = other.roles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRolesIsMutable();
            roles_.addAll(other.roles_);
          }
          onChanged();
        }
        if (!other.permissions_.isEmpty()) {
          if (permissions_.isEmpty()) {
            permissions_ = other.permissions_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePermissionsIsMutable();
            permissions_.addAll(other.permissions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amur.home.auth.rpc.AuthServiceProto.UserAuth parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amur.home.auth.rpc.AuthServiceProto.UserAuth) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRolesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          roles_ = new com.google.protobuf.LazyStringArrayList(roles_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string roles = 3;</code>
       * @return A list containing the roles.
       */
      public com.google.protobuf.ProtocolStringList
          getRolesList() {
        return roles_.getUnmodifiableView();
      }
      /**
       * <code>repeated string roles = 3;</code>
       * @return The count of roles.
       */
      public int getRolesCount() {
        return roles_.size();
      }
      /**
       * <code>repeated string roles = 3;</code>
       * @param index The index of the element to return.
       * @return The roles at the given index.
       */
      public java.lang.String getRoles(int index) {
        return roles_.get(index);
      }
      /**
       * <code>repeated string roles = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the roles at the given index.
       */
      public com.google.protobuf.ByteString
          getRolesBytes(int index) {
        return roles_.getByteString(index);
      }
      /**
       * <code>repeated string roles = 3;</code>
       * @param index The index to set the value at.
       * @param value The roles to set.
       * @return This builder for chaining.
       */
      public Builder setRoles(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
        roles_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       * @param value The roles to add.
       * @return This builder for chaining.
       */
      public Builder addRoles(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
        roles_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       * @param values The roles to add.
       * @return This builder for chaining.
       */
      public Builder addAllRoles(
          java.lang.Iterable<java.lang.String> values) {
        ensureRolesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoles() {
        roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       * @param value The bytes of the roles to add.
       * @return This builder for chaining.
       */
      public Builder addRolesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRolesIsMutable();
        roles_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePermissionsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          permissions_ = new com.google.protobuf.LazyStringArrayList(permissions_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @return A list containing the permissions.
       */
      public com.google.protobuf.ProtocolStringList
          getPermissionsList() {
        return permissions_.getUnmodifiableView();
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @return The count of permissions.
       */
      public int getPermissionsCount() {
        return permissions_.size();
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param index The index of the element to return.
       * @return The permissions at the given index.
       */
      public java.lang.String getPermissions(int index) {
        return permissions_.get(index);
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the permissions at the given index.
       */
      public com.google.protobuf.ByteString
          getPermissionsBytes(int index) {
        return permissions_.getByteString(index);
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param index The index to set the value at.
       * @param value The permissions to set.
       * @return This builder for chaining.
       */
      public Builder setPermissions(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePermissionsIsMutable();
        permissions_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param value The permissions to add.
       * @return This builder for chaining.
       */
      public Builder addPermissions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePermissionsIsMutable();
        permissions_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param values The permissions to add.
       * @return This builder for chaining.
       */
      public Builder addAllPermissions(
          java.lang.Iterable<java.lang.String> values) {
        ensurePermissionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, permissions_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPermissions() {
        permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param value The bytes of the permissions to add.
       * @return This builder for chaining.
       */
      public Builder addPermissionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePermissionsIsMutable();
        permissions_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amur.home.auth.rpc.UserAuth)
    }

    // @@protoc_insertion_point(class_scope:com.amur.home.auth.rpc.UserAuth)
    private static final com.amur.home.auth.rpc.AuthServiceProto.UserAuth DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amur.home.auth.rpc.AuthServiceProto.UserAuth();
    }

    public static com.amur.home.auth.rpc.AuthServiceProto.UserAuth getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserAuth>
        PARSER = new com.google.protobuf.AbstractParser<UserAuth>() {
      @java.lang.Override
      public UserAuth parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserAuth(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserAuth> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserAuth> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amur.home.auth.rpc.AuthServiceProto.UserAuth getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amur_home_auth_rpc_GetAuthByIdRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amur_home_auth_rpc_GetAuthByIdRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amur_home_auth_rpc_GetAuthByIdResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amur_home_auth_rpc_GetAuthByIdResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amur_home_auth_rpc_UserAuth_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amur_home_auth_rpc_UserAuth_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\026com.amur.home.auth.rpc\032\037go" +
      "ogle/protobuf/timestamp.proto\" \n\022GetAuth" +
      "ByIdRequest\022\n\n\002id\030\001 \001(\003\"E\n\023GetAuthByIdRe" +
      "sponse\022.\n\004auth\030\001 \001(\0132 .com.amur.home.aut" +
      "h.rpc.UserAuth\"L\n\010UserAuth\022\n\n\002id\030\001 \001(\003\022\020" +
      "\n\010password\030\002 \001(\t\022\r\n\005roles\030\003 \003(\t\022\023\n\013permi" +
      "ssions\030\004 \003(\t2w\n\013AuthService\022h\n\013GetAuthBy" +
      "Id\022*.com.amur.home.auth.rpc.GetAuthByIdR" +
      "equest\032+.com.amur.home.auth.rpc.GetAuthB" +
      "yIdResponse\"\000B,\n\026com.amur.home.auth.rpcB" +
      "\020AuthServiceProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_amur_home_auth_rpc_GetAuthByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amur_home_auth_rpc_GetAuthByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amur_home_auth_rpc_GetAuthByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_amur_home_auth_rpc_GetAuthByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_amur_home_auth_rpc_GetAuthByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amur_home_auth_rpc_GetAuthByIdResponse_descriptor,
        new java.lang.String[] { "Auth", });
    internal_static_com_amur_home_auth_rpc_UserAuth_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_amur_home_auth_rpc_UserAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amur_home_auth_rpc_UserAuth_descriptor,
        new java.lang.String[] { "Id", "Password", "Roles", "Permissions", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
