server:
  port: 80
spring:
  application:
    name: home-gateway
  banner:
    location: banner.txt
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: home-user
          uri: lb://home-user
          predicates:
            - Path=/home-user/**
        - id: home-tinyid
          uri: lb://home-tinyid
          predicates:
            - Path=/home-tinyid/**
        - id: home-sba
          uri: lb://home-sba
          predicates:
            - Path=/home-sba/**
        - id: home-auth
          uri: lb://home-auth
          predicates:
            - Path=/home-auth/**
      #          filters:
      #            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  config:
    import:
      - optional:nacos:home-gateway.yml
#  web:
#    resources:
#      add-mappings: true
grpc:
  server:
    port: 9080

knife4j:
  gateway:
    enable: true
    routes:
      - name: 用户服务
        url: /home-user/v3/api-docs?group=default
        service-name: user-service
        order: 2
      - name: ID服务
        url: /home-tinyid/v3/api-docs?group=default
        service-name: id-service
        order: 3