server:
  port: 8080
spring:
  application:
    name: home-gateway
  banner:
    location: banner.txt
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: home-user
          uri: lb://home-user
          predicates:
            - Path=/home-user/**
        - id: home-tinyid
          uri: lb://home-tinyid
          predicates:
            - Path=/home-tinyid/**
        - id: home-sba
          uri: lb://home-sba
          predicates:
            - Path=/home-sba/**
      #          filters:
      #            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  config:
    import:
      - optional:nacos:home-gateway.yml
#  web:
#    resources:
#      add-mappings: true
grpc:
  server:
    port: 9080

knife4j:
  gateway:
    enable: true
    routes:
      - name: 用户服务
        url: /home-user/v3/api-docs?group=default
        service-name: user-service
        order: 2
      - name: ID服务
        url: /home-tinyid/v3/api-docs?group=default
        service-name: id-service
        order: 3


#amur:
#  jwt:
#    enabled: true   # 是否开启JWT登录认证功能
#    secret: com.amur.home  # JWT 私钥，用于校验JWT令牌的合法性
#    expiration: 3600000 # JWT 令牌的有效期，用于校验JWT令牌的合法性，一个小时
#    header: Authorization # HTTP 请求的 Header 名称，该 Header作为参数传递 JWT 令牌
#    userParamName: userId  # 用户登录认证用户名参数名称
#    pwdParamName: password  # 用户登录认证密码参数名称
#    useDefaultController: true # 是否使用默认的JwtAuthController
#    skipValidUrl: /auth/login,/actuator/**,/swagger-ui.html,/swagger-resources/**,/v3/api-docs,/webjars/**,/doc.html,/home-user/v3/api-docs,/home-tinyid/v3/api-docs